package com.example.bakeryapp.util


data class ItemData(
    var itemId: String = "", //auto generated by firebase!
    var name: String = "",
    var image: String = "https://i.ibb.co/W3mwh3v/bun.png", // default image
    var description: String = "",
    var cost: Int = -1,
    var currency: String = "shekel" //default is shekel
)
