package com.example.bakeryapp.util


data class ItemData(
    var itemId: String = "", //auto generated by firebase!
    var name: String = "",
    var description: String = "",
    var cost: Int = -1,
    var currency: String = "shekel" //default is shekel
)
