package com.example.bakeryapp.util

data class OrdersData(
    var orderId: String = "", //auto generated by firebase!
    var userId: String = "",
    var list: MutableList<OrderItem>
) {
    constructor() : this("","", mutableListOf())
}

data class OrderItem(
    var itemId: String = "",
    var amount: Int = 0
)
