package com.example.bakeryapp.util

data class OrdersDataPopulated(
    var orderId: String = "", //auto generated by firebase!
    var userId: String = "",
    var userName:String = "",
    var list: MutableList<OrderItemPopulated>,
    var totalPrice: Int = 0,
    var date: String = ""
) {
    constructor() : this("", "","", mutableListOf())
}

data class OrderItemPopulated(
    var item: ItemData? = null,
    var amount: Int = 0,
)

data class OrdersData(
    var orderId: String = "", //auto generated by firebase!
    var userId: String = "",
    var userName:String = "",
    var list: MutableList<OrderItem>,
    var totalPrice: Int = 0,
    var date: Long = 0
) {
    constructor() : this("","", "", mutableListOf())
    constructor(userId: String, userName:String, list: MutableList<OrderItem>) : this("", userId, userName, list)
}

data class OrderItem(
    var itemId: String = "",
    var amount: Int = 0,
)
